using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using BusinessLogic;
using System.Configuration;
using System.IO;

namespace BikeAble.Client
{
    public partial class CodeQR : System.Web.UI.Page
    {
        Random rnd = new Random(DateTime.Now.Millisecond);
        protected void Page_Load(object sender, EventArgs e)
        {
            if (Session["connected"] != null)
            {
                PasswordAlert.Visible = false;
                User user = (User)Session["user"];
                CommandeFactory CMMF = new CommandeFactory(ConfigurationManager.ConnectionStrings["cnn1"].ConnectionString);
                ID_QR.Value = CMMF.GetLastCommandeFromUser(user.ID_User).ToString();
                Commande c = CMMF.GetByID(Int32.Parse(ID_QR.Value));
                if(c.IDClientRec_Commande == 0)
                {
                    string pwd = GetPwd(Rng(0, 225));
                    TextPwd.InnerText += " "+pwd;
                    PasswordAlert.Visible = true;
                }
            }

            
        }

        protected void Retour_Click(object sender, EventArgs e)
        {
            Response.Redirect("Livraisons.aspx");
        }

        protected int Rng(int min, int max)
        {            
            return rnd.Next(min, max);
        }

        protected string GetPwd(int line)
        {
            string[] array = new string[225]{"Tique"
            ,"Transpirer"
            ,"Tondre"
            ,"Courageux"
            ,"Dragon"
            ,"Collectionneur"
            ,"Cavalier"
            ,"Clairon"
            ,"Péruvien"
            ,"Lavandre"
            ,"Échelon"
            ,"Heure"
            ,"Moule"
            ,"Querelle"
            ,"Vierge"
            ,"Paysan"
            ,"Peau"
            ,"Clavier"
            ,"Examen"
            ,"Propreté"
            ,"Poker"
            ,"Cerveau"
            ,"Minute"
            ,"Asie"
            ,"Capsule"
            ,"Disquette"
            ,"Éponge"
            ,"Catalogne"
            ,"Visite"
            ,"Illusion"
            ,"Arme"
            ,"Enclume"
            ,"Licorne"
            ,"Canard"
            ,"Règle"
            ,"Clair"
            ,"Haleter"
            ,"Écureuil"
            ,"Dur"
            ,"Remuer"
            ,"Résumer"
            ,"Panthéon"
            ,"Romain"
            ,"Carte"
            ,"Page"
            ,"Pastille"
            ,"Ferme"
            ,"Défense"
            ,"Échelle"
            ,"Fiche"
            ,"Cométique"
            ,"Pantalon"
            ,"Étoile"
            ,"Pluie"
            ,"Tasse"
            ,"Peindre"
            ,"Épaule"
            ,"Escargot"
            ,"Pomme"
            ,"Guitare"
            ,"Chaud"
            ,"Avion"
            ,"Chaise"
            ,"Jambe"
            ,"Médecin"
            ,"Transport"
            ,"Magasin"
            ,"Plat"
            ,"Camion"
            ,"Casserole"
            ,"Genou"
            ,"Bonbons"
            ,"Bacon"
            ,"Anneau"
            ,"Tarte"
            ,"Boisson"
            ,"Bouche"
            ,"Robe"
            ,"Tapis"
            ,"Brosse"
            ,"Lion"
            ,"Vis"
            ,"Boucle"
            ,"Chat"
            ,"Chien"
            ,"Bras"
            ,"Jambe"
            ,"Lapin"
            ,"Girafe"
            ,"Feuille"
            ,"Grand"
            ,"Chemise"
            ,"Glace"
            ,"Sac"
            ,"Serpant"
            ,"Silence"
            ,"Visage"
            ,"Cerise"
            ,"Parapluie"
            ,"Sofa"
            ,"Lumière"
            ,"Kiwi"
            ,"Fusée"
            ,"Craquelin"
            ,"Marche"
            ,"Carotte"
            ,"Loup"
            ,"Porte"
            ,"Baudet"
            ,"Maison"
            ,"Stylo"
            ,"Football"
            ,"Botte"
            ,"Tapis"
            ,"Fauteuil"
            ,"Cercle"
            ,"Vert"
            ,"Abri"
            ,"Train"
            ,"Coffre"
            ,"Fiche"
            ,"Été"
            ,"Cube"
            ,"Fromage"
            ,"Marguerite"
            ,"Éviter"
            ,"Tortue"
            ,"Papillon"
            ,"Verre"
            ,"Lunette"
            ,"Poignet"
            ,"Source"
            ,"Pelle"
            ,"Serviette"
            ,"Bateau"
            ,"Bus"
            ,"Paume"
            ,"Nuage"
            ,"Oignon"
            ,"Abeille"
            ,"Loup"
            ,"Baleine"
            ,"Bain"
            ,"Poussin"
            ,"Coffre"
            ,"Glace"
            ,"Trompette"
            ,"Café"
            ,"Spaghetti"
            ,"Étudiant"
            ,"Noir"
            ,"Lézard"
            ,"Taxi"
            ,"Rayon"
            ,"Bleu"
            ,"Poulpe"
            ,"Bleu"
            ,"Automne"
            ,"Tableau"
            ,"Plage"
            ,"Rose"
            ,"Cercle"
            ,"Vent"
            ,"Tigre"
            ,"Orange"
            ,"Herbe"
            ,"Arbre"
            ,"Cuisinier"
            ,"Panier"
            ,"Tomate"
            ,"Triangle"
            ,"Hibou"
            ,"Tasse"
            ,"Ours"
            ,"Bouche"
            ,"Comète"
            ,"Cheveux"
            ,"Mur"
            ,"Banane"
            ,"Fiche"
            ,"Lune"
            ,"Lait"
            ,"Évier"
            ,"Hiver"
            ,"Viande"
            ,"Craie"
            ,"Cinq"
            ,"Manchot"
            ,"Poivre"
            ,"Sel"
            ,"Fille"
            ,"Poulet"
            ,"Poule"
            ,"Sourcil"
            ,"Loupe"
            ,"Tomate"
            ,"Soldat"
            ,"Hiver"
            ,"Goupille"
            ,"Citrouille"
            ,"Requin"
            ,"Sommeil"
            ,"Lent"
            ,"Terrain"
            ,"Fourchette"
            ,"Bocal"
            ,"Éclair"
            ,"Brun"
            ,"Oreille"
            ,"Aigle"
            ,"Dauphin"
            ,"Taxi"
            ,"Pneu"
            ,"Pêche"
            ,"Panda"
            ,"Koala"
            ,"Montagne"
            ,"Cheval"
            ,"Écran"
            ,"Téléphone"
            ,"Plafond"
            ,"Jupe"
            ,"Clé"
            ,"Route"
            ,"Écouteur"};
            return array[line];           
        }
    }
}